version: '3.3'
services:
  metricbeat:
    build: ./metricbeat
    environment:
      URL_PING: ""
      URL_HTTP_ENDPOINT: ""
      LOGSTASH_URL: ""
      LOGSTASH_PORT:

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.1
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m

  kibana:
    image: docker.elastic.co/kibana/kibana:5.6.1
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "true"
    ports:
      - "5601:5601"
