version: '3.3'
services:
  metricbeat:
    build: ./metricbeat
    container_name: metricbeat
    environment:
      ELASTICSEARCH_URL: "elasticsearch:9200"
      KIBANA_URL: "kibana:5601"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.0.0
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
      ES_JAVA_OPTS: -Xms1024m -Xmx1024m

  kibana:
    image: docker.elastic.co/kibana/kibana:6.0.0
    environment:
      ELASTICSEARCH_URL: "http://elasticsearch:9200"
      XPACK_SECURITY_ENABLED: "true"
    ports:
      - "5601:5601"
